version: 2.1

# Define the jobs we want to run for this project
jobs:
  print_hello:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "Hello "
  print_world:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "World"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
