version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:10.8.0
    working_directory: ~/LearnCI
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node-modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:10.8.0
    working_directory: ~/LearnCI
    steps:
      - checkout
      - run: npm i
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:10.8.0
    working_directory: ~/LearnCI
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
